"""
Password hashing: scrypt (hashlib, stdlib - no external dependency), chosen
over bcrypt because it is memory-hard and because scrypt's salt is an
explicit keyword argument, which lets a second secret (the pepper) be
layered on top without fighting the KDF's own API - see the branch
decision this was built against.

Two secrets go into every hash, and they play different roles:
  - salt: unique per user, generated by generate_salt(), stored in the
    users table right next to the hash. Its whole job is making two
    users' identical passwords hash differently; it is NOT meant to be
    secret from anyone with DB access.
  - pepper: one single value for the entire application, read from the
    KUNGFU_CHESS_PASSWORD_PEPPER environment variable and NEVER written
    to the database, a config file, or source control. Its job is that
    a stolen DB alone (schema + rows, no server env) is not enough to
    brute-force any password - see .env.example.

WHY MISSING PEPPER FAILS LOUDLY (RuntimeError) INSTEAD OF FALLING BACK TO
A DEFAULT:
a silent default would mean every deployment that forgot to set the env
var hashes passwords with a pepper an attacker can guess (because it's
sitting in this file, in git). Refusing to run is the only behavior that
can't quietly downgrade security.
"""

import hashlib
import hmac
import os

PEPPER_ENV_VAR = "KUNGFU_CHESS_PASSWORD_PEPPER"

_SALT_LENGTH_BYTES = 16
_SCRYPT_N = 2 ** 14
_SCRYPT_R = 8
_SCRYPT_P = 1
_DERIVED_KEY_LENGTH_BYTES = 64


def generate_salt() -> bytes:
    return os.urandom(_SALT_LENGTH_BYTES)


def hash_password(password: str, salt: bytes) -> bytes:
    pepper = _read_pepper()
    return hashlib.scrypt(
        password.encode("utf-8") + pepper,
        salt=salt,
        n=_SCRYPT_N,
        r=_SCRYPT_R,
        p=_SCRYPT_P,
        dklen=_DERIVED_KEY_LENGTH_BYTES,
    )


def verify_password(password: str, salt: bytes, expected_hash: bytes) -> bool:
    candidate = hash_password(password, salt)
    return hmac.compare_digest(candidate, expected_hash)


def _read_pepper() -> bytes:
    pepper = os.environ.get(PEPPER_ENV_VAR)
    if not pepper:
        raise RuntimeError(
            f"{PEPPER_ENV_VAR} environment variable is not set. "
            "This must be a secret, application-wide value known only to "
            "this server process - see .env.example. Refusing to hash or "
            "verify passwords without it rather than falling back to an "
            "insecure default."
        )
    return pepper.encode("utf-8")